### ISSUE TITLE
Function serialization

### ISSUE THREAD

**Issue by Ambrevar** [40ants/cl-prevalence#3]
Working on [Next](https://github.com/atlas-engineer/next) I have to deal with many structure / class slots whose values are function names (e.g. `#'format`) since they are configuration variables set by the user.

It'd be nice to be able to serialize those functions in the `#'` printed representation.
The problem is that the user could technically also specify a lambda, which is not serializable (unless we try really hard, but let's skip that).

So what about adding support for named functions?
Here is an example for  s-exp serialization:

```lisp
(defmethod serialize-sexp-internal ((object function) stream serialization-state)
  "Serialize function OBJECT.
If the function is named FOO, serialized is to \"#'FOO\".
Note: Function serialization is not part of the original cl-prevalence."
  (declare (ignore serialization-state))
  (let ((function-symbol (nth-value 2 (function-lambda-expression object))))
    (unless (symbolp function-symbol)
      (error "Cannot serialize anonymous functions (lambdas)"))
    (write-string "(:FUNCTION . " stream)
    (print-symbol function-symbol stream)
    (write-string ")" stream)))
```

Then at the end of `deserialize-sexp-internal`:

```
(:function (symbol-function (rest sexp)))
```

Thoughts?

**Comment by Ambrevar** [comment]
@svetlyak40wt Friendly ping! :)  Any thought on this?

**Comment by svetlyak40wt** [comment]
I think, that is is bad practice, because this way we'll break semantic of serialization – only the name will be saved, not the value.

If you want to let users use functions in configs, then nudge them to use symbols. Symbols are funcallable and they can be serialized without additional changes to cl-prevalence.

Also, using symbols you explicitly saying: "We are saving the function's name not the value! The value can change in future when the config will be restored."

**Comment by Ambrevar** [comment]
This is a very good point!
Maybe this comment deserves an entry in the documentation ;)
Closing since serialization functions should cut it for me then.
